spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labs_spring
    username: sw
    password: 22380476
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true